name: Build Qemu

on:
  push:
    branches:
      - qemu

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        version:
          - stable-9.2
    steps:
      - name: Git Settings
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: fetch branch name
        id: vars
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Install Dependency
        run: |
          sudo apt-get update
          echo "install package for building qemu-user" 
          sudo apt-get install -y git gcc make build-essential libglib2.0-dev libpixman-1-dev zlib1g-dev python3-venv ninja-build flex bison
          
      - name: Restore Code
        id: cache-code
        uses: actions/cache@v4
        env:
          cache-name: cache-qemu-code
        with:
          path: qemu
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.version }} 
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.version }} 

      - if: ${{ steps.cache-code.outputs.cache-hit != 'true' }}
        name: Fetching Code
        continue-on-error: false
        run: |
          git clone https://gitlab.com/qemu-project/qemu.git -b ${{ matrix.version }} --depth 1
      
      - if: ${{ steps.cache-code.outputs.cache-hit != 'true' }}
        name: Compile Qemu
        run: |
          cd qemu
          ./configure --disable-system --disable-bsd-user --enable-linux-user --static --enable-strip --disable-debug-info --prefix=$PWD/INSTALL
          make -j$(nproc)
          make install
      
      - name: tar binary
        run: |
          cd qemu/INSTALL
          rm -f ../${{ matrix.version }}.tar.gz
          tar -zxvf ../${{ matrix.version }}.tar.gz .

      - name: Create/Update Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "qemu/${{ matrix.version }}.tar.gz"
          draft: false
          tag: qemu-user-static-${{ matrix.version }}
          name: 'qemu-user-static-${{ matrix.version }}'
          replacesArtifacts: true
          removeArtifacts: true
          generateReleaseNotes: true

